name: test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
    - 
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - 
      name: regenerate dist/index.js
      run: |
        npm i @vercel/ncc --save-dev
        npm install
        PATH=$PATH:./node_modules/.bin ncc build index.js
    - 
      uses: ./
      with:
        macos: echo "Hi from macos"
        linux: |
          echo "Hi from linux"
          echo "Hi from linux second line"
        windows: echo "Hi from windows"
    - 
      uses: ./
      with:
        macos: echo "test2"
        linux: echo "test2"
        windows: echo "test2"
    - 
      uses: knicknic/os-specific-run@master
      with:
        macos: echo "Hi from macos"
        linux: |
          echo "Hi from linux"
          echo "Hi from linux second line"
        windows: echo "Hi from windows"
    - 
      uses: knicknic/os-specific-run@master
      with:
        macos: echo "test2"
        linux: echo "test2"
        windows: echo "test2"
    - 
      if: startsWith(matrix.os,'ubuntu')
      name: Check for modified files
      id: git-check
      run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
    - 
      name: Push changes
      if: startsWith(matrix.os,'ubuntu') && steps.git-check.outputs.modified == 'true'
      run: |
        git config --global user.name 'Nick Maliwacki'
        git config --global user.email 'knic.knic@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Regenerate dist/index.js"
        git push
